### ISSUE TITLE
validator issues vs. Django issues

### ISSUE THREAD

**Issue by smeylan** [langcog/peekbank#16]
Right now it is hard to determine if errors in the db population are because of violations in expectations (missing CSVs, bad data types, etc.) or if there is an edge case in the Django population code. It would be great to have a better way to determine which one is which, especially to flag input-related issues that get past the validator

**Comment by lingerxu** [comment]
Validator now does check for missing CSVs and bad data types.

**Comment by smeylan** [comment]
@lingerxu  @JMankewitz Do we want the validator to check for missing indices as well? This is the main thing that is hard for me to distinguish between validator and Django issues. Maybe in the validator do test merges and check if there are missing records? Should be reasonably fast.

**Comment by lingerxu** [comment]
Sure. Just make sure that foreign keys are referenced?
