### ISSUE TITLE
Source for distractor labels?

### ISSUE THREAD

**Issue by smeylan** [langcog/peekbank#18]
@mzettersten points out that under the schema in mid-March 2021, the distractor stimulus labels (`original_stimulus_label` and `english_stimulus_label`) have a somewhat odd status. Whereas the target is directly named in the experiment, it is not always clear where the distractor stimulus label comes from. In some cases it is provided somewhere else in the experiment (e.g. in designs where the target appears elsewhere, as we originally considered in development), but this isn't true whenever the distractor is a novel item (as noted by @cbergey), or in multilingual designs where it is unclear what  the non-English distractor label should be.

The proposed solution is as follows:
- Adding a `image_description` field (possibly null) with a natural language description of the distractor. This can be multiple words, e.g., `purple elephant,` depending on the task. This is closely related to a proposed `unilemma` field. The `image_description` field could be more specific than the  `original_stimulus_label` field, for example "cat" and "animal", respectively
- Adding a `image_description_source` (possibly null) with notes on where the natural language description came from. Options would include `image path`, `experiment documentation`, `Peekbank discretion`
- Keeping the `stimulus_image_path` field unchanged
- Specifying "None" for  `original_stimulus_label` and `english_stimulus_label` when no label is available, for example for a novel word (as already permitted by the database)

This solution keeps stimuli defined as image<->label / potential label links (rather than breaking into separate visual and auditory stimuli), allows end-users to select stimuli (and hence trials) according to a natural language description of their contents, allows end-users to filter stimuli (and hence trials) by those that are experiment-specified vs. those added by Peekbank. It also allows for end-users to retrieve visual embeddings by label (e.g. using VGG-19) for both targets and distractors, even if the experiment does not explicitly state a label for the stimulus.

All dataset processing scripts will need to be revisited to specify these fields.

**Comment by smeylan** [comment]
Martin asks, What are the guidelines we can give to data importers as to when they should include additional distractor records? 

I can see a few cases here:
1. standard distractor-appears-as-target: one set of stimuli gets re-used as both. if cat (id= 1) appears as distractor for dog (id = 2), then trial 1 specified target_id = 1 and distractor_id=2. If dog is the target later, the trial says target_id = 2 and distractor_id = 1.

2. distractor-is-never-mentioned-but-is-named-in-the-file: named stimuli appear as records like in 1), then there are also additional records for the distractors. An experiment with familiar targets and  novel, unnamed distractors,  e.g., cat=1, dog=2, wug=3, dax=4, would have trial 1, target_id = 1, distractor_id = 3; trial 2, target_id = 2, distractor_id = 4. Distractors would have image_description "wug" and "dax", image_description_source of "image_path",  original_stimulus_label and english_stimulus_label set to "none". 

3. distractor-is-never-mentioned-and-not-named-in-the-file: named stimuli appear as records like in 1), then there are also additional records for the distractors. An experiment with familiar targets and  novel, unnamed distractors,  e.g., cat=1, dog=2, wug=3, dax=4, would have trial 1, target_id = 1, distractor_id = 3; trial 2, target_id = 2, distractor_id = 4. Distractors would have image_description of "novel", image_description_source of "Peekbank discretion",  original_stimulus_label and english_stimulus_label set to "none".

4. Other cases where the distractor is more ambiguous?

**Comment by smeylan** [comment]
4. Different-trials-have-same-image-different-labels ("ambiguity"): examples include hyponymy, synonymy, multiple labels for the thing. In these cases, each label-image pair gets a separate row in the stimulus table. If it's a distractor and the label is unclear, the label is None, and it has only one row

**Comment by adriansteffan** [comment]
I think this discussion has been moved to the peekbank import repo quite some time ago and currently lives in the code review checklists. will include it in the documentation there!
