### ISSUE TITLE
dataset table needs descriptive fields

### ISSUE THREAD

**Issue by mcfrank** [langcog/peekbank#2]
we probably want fields including:

* name - a descriptive label, could be a shortcite
* shortcite - e.g. "Yurovsky et al., under review"
* cite - e.g. "Yurovsky, D., Wade, A., Kraus, A. M., Gengoux, G. W., Hardan, A. Y., Frank, M. C. (under review). Developmental changes in the speed of social attention in early word learning."

then we can propagate these to the UI...

**Comment by mikabr** [comment]
added

**Comment by mzettersten** [comment]
we also have a a fourth character field, in datasets, called lab_dataset_id, which I think we've been using for lab-internal names (e.g., "reflook_v1"). So we have:

- lab_dataset_id
- name
- shortcite
- cite

Just to check: Do we need all four, or is one of these redundant? I'm mainly wondering if name is redundant with lab_dataset_id

**Comment by mcfrank** [comment]
I think name is redundant? lab_dataset_id is the human readable name (e.g.
"reflook_v1") that we use for filenames etc?

**Comment by mzettersten** [comment]
Yeah, I think we ultimately decided to keep all four for now in the schema ("name" is now "dataset_name") with the idea that lab_dataset_id can now be something more lab-specific/-internal, and "our" peekbank dataset_name can potentially be something different. I think in practice it could end up that lab_dataset_id and dataset_name are the same thing for most datasets.

**Comment by mzettersten** [comment]
Here's a good example actually - the pomper & saffran 2016 study's Saffran-lab-internal name is "SwitchingCues", but I don't think we've used that name at all in handling the dataset. So that's one way we could use the lab_dataset_id column, to keep these lab-internal identifiers for easier communication/ disambiguation with their labs of origin.
